### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by Gelioks** [Sub-7/FFmpegUI#2]
Just tried v2 installation on Debian (Proxmox) not working. 2 repos added by the script are not accessible. Therefore, my understanding, that Apache is also not installed (service command won't show it as installed) and apache2.conf file is missing.
Options chosen when installing: 1,7,8.

Also please add apache2-utils in the list of dependencies, so htpasswd can be run.

**Comment by Sub-7** [comment]
Hey, you're quick, thanks for the message.
Current version is for Ubuntu 18.04
2.0 will be for Ubuntu 20.04.
2.0 is coming today, final tests are in progress.
If you see updates in the read.me then it's time.
